name: Setup

inputs:
  python-version:
    required: false
    default: '3.10'
  torch-version:
    required: false
    default: '2.3.0'
  pyg-version:
    required: false
    default: '2.5.3'
  cuda-version:
    required: false
    default: cpu
  full_install:
    required: false
    default: true

runs:
  using: composite

  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}
        cache: 'pip'
        cache-dependency-path: pyproject.toml

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        pip install torch==${{ inputs.torch-version }} --extra-index-url https://download.pytorch.org/whl/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash

    - name: Install PyTorch ${{ inputs.torch-version }}+${{ inputs.cuda-version }}
      if: ${{ inputs.torch-version == 'nightly' }}
      run: |
        pip install --pre torch --extra-index-url https://download.pytorch.org/whl/nightly/${{ inputs.cuda-version }}
        python -c "import torch; print('PyTorch:', torch.__version__)"
        python -c "import torch; print('CUDA available:', torch.cuda.is_available())"
        python -c "import torch; print('CUDA:', torch.version.cuda)"
      shell: bash

    - name: Install pyg
      if: ${{ inputs.torch-version != 'nightly' }}
      run: |
        pip install torch_geometric==${{ inputs.pyg-version }}
      shell: bash

    - name: Install faiss-cpu
      if: ${{ inputs.full_install == 'true' && inputs.cuda-version == 'cpu' && runner.os != 'macOS' }}
      run: |
        pip install faiss-cpu
      shell: bash

    - name: Install faiss-gpu
      if: ${{ inputs.full_install == 'true' && inputs.cuda-version != 'cpu' }}
      run: |
        pip install faiss-gpu
      shell: bash
