name: Sphinx docs to gh-pages

on:
  push:
    branches:
      - main

# workflow_dispatch:        # Un comment line if you also want to trigger action manually

jobs:
  sphinx_docs_to_gh-pages:
    runs-on: ubuntu-22.04
    name: Sphinx docs to gh-pages
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      # Skip workflow if only certain files have been changed.
      - name: Get changed files
        id: changed-files-specific
        uses: tj-actions/changed-files@v41
        with:
          files: |
            benchmark/**
            examples/**
            README.md
            CHANGELOG.md
            requirements.txt
            setup.py
            pyproject.toml

      - name: Setup packages
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: ./.github/actions/setup
        with:
          full_install: false

      - name: Install main package
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        run: |
          pip install -e .[docs]

      - name: Running the Sphinx to gh-pages Action
        if: steps.changed-files-specific.outputs.only_changed != 'true'
        uses: uibcdf/action-sphinx-docs-to-gh-pages@v2.1.0
        with:
          branch: main
          dir_docs: docs
          sphinx-apidoc-opts: '--separate -o ./source/_include ../pyg_spectral'
          sphinx-apidoc-exclude: '../*setup* ../*.ipynb'
          sphinx-opts: ''
